name: Rust

on: [push]

jobs:
  test:
    name: Test the project on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
        if: matrix.os == 'macOS-latest'
      - name: Configure path
        run: source $HOME/.cargo/env
        if: matrix.os == 'macOS-latest'
      - name: Debug
        run: echo $PATH && cat $HOME/.cargo/env && echo $PATH
        if: matrix.os == 'macOS-latest'
      - name: Run tests
        run: echo $PATH && cargo test --verbose
