name: Test suite

on: [push]

jobs:
  test:
    name: Test the project on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@master
      - name: Install Rust (macOS)
        run: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
        if: matrix.os == 'macOS-latest'
      - name: Configure cargo (macOS)
        run: ln -s $HOME/.cargo/bin/cargo /usr/local/bin/cargo
        if: matrix.os == 'macOS-latest'
      - name: Run tests
        run: cargo test --verbose
